# Generated by Django 5.1.3 on 2024-11-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_player_game_alter_game_game_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
