# Generated by Django 5.1.3 on 2024-11-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_position_player_phone_number_player_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhouse',
            name='house',
        ),
        migrations.AddField(
            model_name='matchhouse',
            name='house1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_house1', to='home.house'),
        ),
        migrations.AddField(
            model_name='matchhouse',
            name='house2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_house2', to='home.house'),
        ),
    ]
