# Generated by Django 5.1.3 on 2024-11-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_matchhouse_house_matchhouse_house1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchstatistic',
            name='house',
        ),
        migrations.AddField(
            model_name='matchstatistic',
            name='house1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_statistics_as_house1', to='home.house'),
        ),
        migrations.AddField(
            model_name='matchstatistic',
            name='house2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_statistics_as_house2', to='home.house'),
        ),
    ]
