# Generated by Django 5.1.3 on 2024-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_matchstatistic_house_matchstatistic_house1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
