# Generated by Django 5.1.3 on 2024-11-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_game_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.house'),
        ),
    ]
