# Generated by Django 5.1.3 on 2024-11-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_game_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='house',
        ),
        migrations.AddField(
            model_name='game',
            name='house1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_house1', to='home.house'),
        ),
        migrations.AddField(
            model_name='game',
            name='house2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_house2', to='home.house'),
        ),
    ]
