# Generated by Django 5.1.3 on 2024-11-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_match_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='game_id',
            new_name='game',
        ),
    ]
