# Generated by Django 5.1.3 on 2024-11-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_match_game_id_match_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='game',
        ),
    ]
