# Generated by Django 5.1.3 on 2024-11-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_match_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='game',
            new_name='game_id',
        ),
    ]
