# Generated by Django 5.1.3 on 2024-11-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_game_match_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='game_id',
        ),
        migrations.AddField(
            model_name='match',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.game'),
        ),
    ]
