# Generated by Django 5.1.3 on 2024-11-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_team_house_alter_team_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='house1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='house2',
        ),
        migrations.AddField(
            model_name='game',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.house'),
        ),
    ]
