# Generated by Django 5.1.3 on 2024-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_game_house1_remove_game_house2_game_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='captain_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
